{% set version = "1.1.11" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-presenceabsence
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/PresenceAbsence_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/PresenceAbsence/PresenceAbsence_{{ version }}.tar.gz
  sha256: c63a6453783865b7c69c580a09a769e99390dd8b2e0f63e48fbfc86da3bee4b7

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('PresenceAbsence')"           # [not win]
    - "\"%R%\" -e \"library('PresenceAbsence')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=PresenceAbsence
  license: LicenseRef-Unlimited
  summary: This package provides a set of functions useful when evaluating the results of presence-absence models. Package includes functions for calculating threshold dependent measures such as confusion matrices, pcc, sensitivity, specificity, and Kappa, and produces plots of each measure as the threshold is varied. It
    will calculate optimal threshold choice according to a choice of optimization criteria. It also includes functions to plot the threshold independent ROC curves along with the associated AUC (area under the curve).
  license_family: other
  license_file:
    - inst/COPYRIGHTS

extra:
  recipe-maintainers:
    - conda-forge/r
    - colineroyaux

# Package: PresenceAbsence
# Type: Package
# Title: Presence-Absence Model Evaluation.
# Version: 1.1.9
# Date: 2012-08-17
# Depends: R (>= 2.2.0)
# Author: Elizabeth Freeman
# Maintainer: Elizabeth Freeman <eafreeman@fs.fed.us>
# Description: This package provides a set of functions useful when evaluating the results of presence-absence models. Package includes functions for calculating threshold dependent measures such as confusion matrices, pcc, sensitivity, specificity, and Kappa, and produces plots of each measure as the threshold is varied. It will calculate optimal threshold choice according to a choice of optimization criteria. It also includes functions to plot the threshold independent ROC curves along with the associated AUC (area under the curve).
# License: Unlimited
# Packaged: 2012-08-17 18:15:00 UTC; eafreeman
# Repository: CRAN
# Date/Publication: 2012-08-17 18:47:44
